######################################################################################
##                                                                                  ##
## CMake configuration for named plug-in.                                           ##
## This file is auto generated from plugins/config/pluginConf.cmake.in              ##
##                                                                                  ##
## Do not edit this file.                                                           ##
##                                                                                  ##
######################################################################################


# phrasing_uttproc include directories
set(phrasing_uttproc_include_path "/home/matteo/Scrivania/Despeect-ProductBaseline/SpeectInstaller/install/include/speect/plugins/processors/utterances/nlp/phrasify")


# When included in other plug-in CMakeLists.txt, the above
# header directories will be appended to the plug-ins dirs.
list(APPEND ${plugin_lowercase_name}_INCLUDE_DIRS
  ${phrasing_uttproc_include_path}
  )


# phrasing_uttproc version
set(phrasing_uttproc_VERSION_MAJOR 1)
set(phrasing_uttproc_VERSION_MINOR 0)
