/* The SMaryXMLUttFile plug-in SWIG/Python interface definition. */

/*
 * utt_maryxml.i is auto generated by the "speect_plugin_swig_python_interface"
 * macro in speect/swig/python/cmake/swigPythonFunctions.cmake, do not edit utt_maryxml.i
 */

%module(docstring="Speect Plug-in for SMaryXMLUttFile class") utt_maryxml

%pythoncode
%{
	__version__ = "1.0.0"
	__license__= "mit"
%}

/* SWIG includes. */
%include "typemaps.i"
%include "exception.i"

/* Speect Engine header & plug-in headers. */
%header
%{
#include "speect.h"
#include "py_native.h"
%}

/* enable autodoc */
%feature("autodoc", "1");

/* Load the SMaryXMLUttFile class plug-in */
%init
%{
	{
		s_erc rv = S_SUCCESS;
		SPlugin *plugin;


		plugin = s_pm_load_plugin("utt_maryxml.spi", &rv);
		if (rv != S_SUCCESS)
			SWIG_Error(SWIG_RuntimeError, "Failed to load SMaryXMLUttFile plug-in");

		S_UNUSED(plugin);
	}
%}

/* import the Speect Engine Python interface */
%import "/home/matteo/Scrivania/Despeect-ProductBaseline/SpeectInstaller/builds/x86_64-Linux/Speect/engine/swig/python/speect.i"

/* SMaryXMLUttFile SWIG common interface definition. */
%include "/home/matteo/Scrivania/Despeect-ProductBaseline/SpeectInstaller/sources/speect/plugins/serialization/files/utterance/maryxml/swig/python/../common/utt_maryxml_common.c"

/* SMaryXMLUttFile SWIG Python interface definition. */
%include "/home/matteo/Scrivania/Despeect-ProductBaseline/SpeectInstaller/sources/speect/plugins/serialization/files/utterance/maryxml/swig/python/utt_maryxml_python.c"

