######################################################################################
##                                                                                  ##
## CMake configuration for named plug-in.                                           ##
## This file is auto generated from plugins/config/pluginConf.cmake.in              ##
##                                                                                  ##
## Do not edit this file.                                                           ##
##                                                                                  ##
######################################################################################


# hts_engine_synth_uttproc_103 include directories
set(hts_engine_synth_uttproc_103_include_path "/home/matteo/Scrivania/Despeect-ProductBaseline/SpeectInstaller/builds/x86_64-Linux/Speect/plugins/processors/utterances/dsp/sps/hts_engine_103/src;/home/matteo/Scrivania/Despeect-ProductBaseline/SpeectInstaller/sources/speect/plugins/processors/utterances/dsp/sps/hts_engine_103/src;/home/matteo/Scrivania/Despeect-ProductBaseline/SpeectInstaller/install/include;/home/matteo/Scrivania/Despeect-ProductBaseline/SpeectInstaller/sources/speect/plugins/acoustic/audio/src;/home/matteo/Scrivania/Despeect-ProductBaseline/SpeectInstaller/builds/x86_64-Linux/Speect/plugins/acoustic/audio/src")


# When included in other plug-in CMakeLists.txt, the above
# header directories will be appended to the plug-ins dirs.
list(APPEND ${plugin_lowercase_name}_INCLUDE_DIRS
  ${hts_engine_synth_uttproc_103_include_path}
  )


# hts_engine_synth_uttproc_103 version
set(hts_engine_synth_uttproc_103_VERSION_MAJOR 1)
set(hts_engine_synth_uttproc_103_VERSION_MINOR 0)
