# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.




"""Speect Plug-in for SMatrixInt class"""


from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_matrix_int')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_matrix_int')
    _matrix_int = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_matrix_int', [dirname(__file__)])
        except ImportError:
            import _matrix_int
            return _matrix_int
        if fp is not None:
            try:
                _mod = imp.load_module('_matrix_int', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _matrix_int = swig_import_helper()
    del swig_import_helper
else:
    import _matrix_int
del _swig_python_version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


__version__ = "1.0.0"
__license__= "mit"

import speect
class SMatrixInt(_object):
    """

    SMatrixInt(mlist)

    A native Speect class for containing an matrix of integer values.
    Create a new object, that contains an matrix of integer point values.

    :param mlist: A Python list of lists containing only integer values.
    :type mlist: list
    :return: Newly created SMatrixInt object.
    :rtype: SMatrixInt

    """

    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SMatrixInt, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SMatrixInt, name)
    __repr__ = _swig_repr
    __swig_getmethods__["row_count"] = _matrix_int.SMatrixInt_row_count_get
    if _newclass:
        row_count = _swig_property(_matrix_int.SMatrixInt_row_count_get)
    __swig_getmethods__["col_count"] = _matrix_int.SMatrixInt_col_count_get
    if _newclass:
        col_count = _swig_property(_matrix_int.SMatrixInt_col_count_get)

    def __init__(self, im, row_count, col_count):
        """

        SMatrixInt(mlist)

        A native Speect class for containing an matrix of integer values.
        Create a new object, that contains an matrix of integer point values.

        :param mlist: A Python list of lists containing only integer values.
        :type mlist: list
        :return: Newly created SMatrixInt object.
        :rtype: SMatrixInt

        """
        this = _matrix_int.new_SMatrixInt(im, row_count, col_count)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _matrix_int.delete_SMatrixInt
    __del__ = lambda self: None

    def get(self):
        """

        get()

        Return a copy of this SMatrixInt object as a Python list of lists of integer
        values.

        :return: Python list of lists integer values.
        :rtype: list

        """
        return _matrix_int.SMatrixInt_get(self)

SMatrixInt_swigregister = _matrix_int.SMatrixInt_swigregister
SMatrixInt_swigregister(SMatrixInt)

# This file is compatible with both classic and new-style classes.


