# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.




"""Speect Plug-in for STrackInt class"""


from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_track_int')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_track_int')
    _track_int = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_track_int', [dirname(__file__)])
        except ImportError:
            import _track_int
            return _track_int
        if fp is not None:
            try:
                _mod = imp.load_module('_track_int', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _track_int = swig_import_helper()
    del swig_import_helper
else:
    import _track_int
del _swig_python_version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


__version__ = "1.0.0"
__license__= "mit"

import speect
class STrackInt(_object):
    """

    STrackInt(times, mlist)

    A native Speect class for containing an track of integer values. A track
    is a class for storing time aligned coefficients. Each row of a track
    corresponds to a specific time instant. A column of a track is known as a
    channel, while track rows are knows as frames, for example:

    +-------------+---------+------------+------------+------------+
    |             | Times   | Channel 0  | Channel 1  | Channel 2  |
    +=============+=========+============+============+============+
    | **Frame 1** | 0.131   | 12         | 2          | 8          |
    +-------------+---------+------------+------------+------------+
    | **Frame 2** | 0.254   | 52         | 201        | 43         |
    +-------------+---------+------------+------------+------------+
    | **Frame 3** | 0.428   | 21         | 134        | 78         |
    +-------------+---------+------------+------------+------------+

    Create a new object, that contains an track of integer values. Note
    that the time values are still floating point.

    The call to create the above track one would be::

        track = speect.track_int.STrackInt([0.131, 0.254, 0.428], [[12, 2, 8], [52, 201, 43], [21, 134, 78]])

    :param times: A Python list of the time values, floating point.
    :type times: list
    :param mlist: A Python list of lists containing only integer values (frames and channels).
    :type mlist: list
    :return: Newly created STrackInt object.
    :rtype: STrackInt

    """

    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, STrackInt, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, STrackInt, name)
    __repr__ = _swig_repr
    __swig_getmethods__["row_count"] = _track_int.STrackInt_row_count_get
    if _newclass:
        row_count = _swig_property(_track_int.STrackInt_row_count_get)
    __swig_getmethods__["col_count"] = _track_int.STrackInt_col_count_get
    if _newclass:
        col_count = _swig_property(_track_int.STrackInt_col_count_get)

    def __init__(self, times, im):
        """

        STrackInt(times, mlist)

        A native Speect class for containing an track of integer values. A track
        is a class for storing time aligned coefficients. Each row of a track
        corresponds to a specific time instant. A column of a track is known as a
        channel, while track rows are knows as frames, for example:

        +-------------+---------+------------+------------+------------+
        |             | Times   | Channel 0  | Channel 1  | Channel 2  |
        +=============+=========+============+============+============+
        | **Frame 1** | 0.131   | 12         | 2          | 8          |
        +-------------+---------+------------+------------+------------+
        | **Frame 2** | 0.254   | 52         | 201        | 43         |
        +-------------+---------+------------+------------+------------+
        | **Frame 3** | 0.428   | 21         | 134        | 78         |
        +-------------+---------+------------+------------+------------+

        Create a new object, that contains an track of integer values. Note
        that the time values are still floating point.

        The call to create the above track one would be::

            track = speect.track_int.STrackInt([0.131, 0.254, 0.428], [[12, 2, 8], [52, 201, 43], [21, 134, 78]])

        :param times: A Python list of the time values, floating point.
        :type times: list
        :param mlist: A Python list of lists containing only integer values (frames and channels).
        :type mlist: list
        :return: Newly created STrackInt object.
        :rtype: STrackInt

        """
        this = _track_int.new_STrackInt(times, im)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _track_int.delete_STrackInt
    __del__ = lambda self: None

    def get(self):
        """

        get()

        Return a copy of this STrackInt object as a Python tuple, with the first
        element being a list of the track times, and the second element being
        the frame and channel values.

        :return: A tuple, with the first element being a list of the track times, and the second element being the frame and channel values.
        :rtype: tuple

        """
        return _track_int.STrackInt_get(self)

STrackInt_swigregister = _track_int.STrackInt_swigregister
STrackInt_swigregister(STrackInt)

# This file is compatible with both classic and new-style classes.


