/* The SEbmlRead/SEbmlWrite plug-in SWIG/Python interface definition. */

/*
 * ebml.i is auto generated by the "speect_plugin_swig_python_interface"
 * macro in speect/swig/python/cmake/swigPythonFunctions.cmake, do not edit ebml.i
 */

%module(docstring="Speect Plug-in for SEbmlRead/SEbmlWrite class") ebml

%pythoncode
%{
	__version__ = "1.0.0"
	__license__= "mit"
%}

/* SWIG includes. */
%include "typemaps.i"
%include "exception.i"

/* Speect Engine header & plug-in headers. */
%header
%{
#include "speect.h"
#include "py_native.h"
#include "ebml_def.h"
#include "ebml.h"
#include "ebml_id.h"
#include "ebml_read.h"
#include "ebml_write.h"
%}

/* enable autodoc */
%feature("autodoc", "1");

/* Load the SEbmlRead/SEbmlWrite class plug-in */
%init
%{
	{
		s_erc rv = S_SUCCESS;
		SPlugin *plugin;


		plugin = s_pm_load_plugin("ebml.spi", &rv);
		if (rv != S_SUCCESS)
			SWIG_Error(SWIG_RuntimeError, "Failed to load SEbmlRead/SEbmlWrite plug-in");

		S_UNUSED(plugin);
	}
%}

/* import the Speect Engine Python interface */
%import "/home/matteo/Scrivania/Despeect-ProductBaseline/SpeectInstaller/builds/x86_64-Linux/Speect/engine/swig/python/speect.i"

/* SEbmlRead/SEbmlWrite Python documentation strings. */
%include "/home/matteo/Scrivania/Despeect-ProductBaseline/SpeectInstaller/sources/speect/plugins/serialization/formats/ebml/swig/python/ebml_writer_docs.c"
%include "/home/matteo/Scrivania/Despeect-ProductBaseline/SpeectInstaller/sources/speect/plugins/serialization/formats/ebml/swig/python/ebml_reader_docs.c"

/* SEbmlRead/SEbmlWrite SWIG common interface definition. */
%include "/home/matteo/Scrivania/Despeect-ProductBaseline/SpeectInstaller/sources/speect/plugins/serialization/formats/ebml/swig/python/../common/ebml_writer_common.c"
%include "/home/matteo/Scrivania/Despeect-ProductBaseline/SpeectInstaller/sources/speect/plugins/serialization/formats/ebml/swig/python/../common/ebml_reader_common.c"

/* SEbmlRead/SEbmlWrite SWIG Python interface definition. */
%include "/home/matteo/Scrivania/Despeect-ProductBaseline/SpeectInstaller/sources/speect/plugins/serialization/formats/ebml/swig/python/ebml_writer_python.c"
%include "/home/matteo/Scrivania/Despeect-ProductBaseline/SpeectInstaller/sources/speect/plugins/serialization/formats/ebml/swig/python/ebml_reader_python.c"

