######################################################################################
##                                                                                  ##
## AUTHOR  : Aby Louw                                                               ##
## DATE    : 9 November 2009                                                        ##
##                                                                                  ##
######################################################################################
##                                                                                  ##
## CMake Speect Engine library configuration (SpeectConf.cmake) installer           ##
## speect_conf_install.cmake is auto generated by CMakeLists.txt, do not            ##
## edit speect_conf_install.cmake.                                                  ##
##                                                                                  ##
## We do this because it seems that CMake does not load cache variables             ##
## for the install scripts (e.g SPCT_INCLUDE_DIRS, SPCT_VERSION, ...).              ##
##                                                                                  ##
## Note that this script is only set if SPCT_UNIX is true.                          ##
##                                                                                  ##
######################################################################################


#------------------------------------------------------------------------------------#
#                        Speect Engine include directories                           #
#------------------------------------------------------------------------------------#

set(SPCT_INCLUDE_DIRS "${CMAKE_INSTALL_PREFIX}/include/speect/engine/")


#------------------------------------------------------------------------------------#
#                        Speect Engine version info                                  #
#------------------------------------------------------------------------------------#

set(SPCT_VERSION 1.1.0)
set(SPCT_VERSION_MAJOR 1)
set(SPCT_VERSION_MINOR 1)
set(SPCT_VERSION_PATCH 0)


#------------------------------------------------------------------------------------#
#                             Configure the file                                     #
#------------------------------------------------------------------------------------#

# All relevant variables must be set before here
configure_file(/home/matteo/Scrivania/Despeect-ProductBaseline/SpeectInstaller/sources/speect/engine/config/SpeectConf.cmake.in 
  /home/matteo/Scrivania/Despeect-ProductBaseline/SpeectInstaller/builds/x86_64-Linux/Speect/engine/cmake/SpeectConf.cmake @ONLY)


#------------------------------------------------------------------------------------#
#                               installation                                         #
#------------------------------------------------------------------------------------#

# grabed signature from cmake_install.cmake
if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/speect/engine" TYPE FILE FILES "/home/matteo/Scrivania/Despeect-ProductBaseline/SpeectInstaller/builds/x86_64-Linux/Speect/engine/cmake/SpeectConf.cmake")
endif(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")


